Repository llm-d/llm-d, pull requests merged in 2025-09, with the labels that each got.

#244 Additional information about UnspecifiedPlatform on GKE
  docs/infra-providers/gke/README.md
Labels: merge-queue

#201 Add notifications for test failures
  .github/workflows/e2e-inference-scheduling-gke.yaml
  .github/workflows/e2e-pd-disaggregation-gke.yaml
Labels: CICD

#223 feat: Add DigitalOcean provider support with inference scheduling and P/D disaggregation deployment
  docs/infra-providers/digitalocean/README.md
  docs/infra-providers/digitalocean/gpu-configs/l40s-values.yaml
  docs/infra-providers/digitalocean/gpu-configs/rtx-4000-ada-values.yaml
  docs/infra-providers/digitalocean/gpu-configs/rtx-6000-ada-values.yaml
  docs/infra-providers/digitalocean/monitoring/inference-gateway-dashboard.json
  docs/infra-providers/digitalocean/monitoring/setup-monitoring.sh
  docs/infra-providers/digitalocean/verify-do-prerequisites.sh
  guides/inference-scheduling/README.md
  guides/inference-scheduling/helmfile.yaml.gotmpl
  guides/inference-scheduling/ms-inference-scheduling/digitalocean-values.yaml
  guides/prereq/infrastructure/README.md
Labels: merge-queue

#161 Add XPU support
  .github/workflows/build-image.yml
  Makefile
  README.md
  docker/Dockerfile.cuda
  docker/Dockerfile.xpu
Labels: hardware-support, needs-rebase

#273 fix XPU ci release workflow trivy step
  .github/workflows/ci-release.yaml
Labels: bug, CICD

#263 Minor Documentation Changes
  guides/prereq/gateway-provider/README.md
  guides/wide-ep-lws/README.md
Labels: documentation
